-- DATABASE POSTGRESQL

-- USERS

CREATE TABLE USERS 
(US_ID_USER 			SERIAL PRIMARY KEY
,US_USERNAME			VARCHAR(100)
,US_HASH				VARCHAR(500)
,US_CREATE_DATETIME		TIMESTAMP DEFAULT CURRENT_TIMESTAMP
,US_CREATE_USER			VARCHAR(100));

